import type { Metadata } from 'next'
import './globals.css'
import { ReactNode } from 'react'
import Header from '@/components/Header/Header'
import Footer from '@/components/Footer/Footer'
import StoreProvider from '@/redux/StoreProvider'

export const metadata: Metadata = {
  title: 'Cars rent',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en">
      <StoreProvider>
        <body className="relative flex min-h-screen w-full flex-col">
          <Header />
          <div className="flex-1">{children}</div>
          <Footer />
        </body>
      </StoreProvider>
    </html>
  )
}
