import { v4 as uuidv4 } from 'uuid';

export const carMakes = [
  { id: uuidv4(), make: "Toyota" },
  { id: uuidv4(), make: "Honda" },
  { id: uuidv4(), make: "Ford" },
  { id: uuidv4(), make: "Chevrolet" },
  { id: uuidv4(), make: "Nissan" },
  { id: uuidv4(), make: "BMW" },
  { id: uuidv4(), make: "Mercedes-Benz" },
  { id: uuidv4(), make: "Volkswagen" },
  { id: uuidv4(), make: "Audi" },
  { id: uuidv4(), make: "Hyundai" },
  { id: uuidv4(), make: "Kia" },
  { id: uuidv4(), make: "Mazda" },
  { id: uuidv4(), make: "Subaru" },
  { id: uuidv4(), make: "Lexus" },
  { id: uuidv4(), make: "Jeep" },
  { id: uuidv4(), make: "Dodge" },
  { id: uuidv4(), make: "Ram" },
  { id: uuidv4(), make: "Tesla" },
  { id: uuidv4(), make: "Volvo" },
  { id: uuidv4(), make: "Porsche" },
  { id: uuidv4(), make: "Land Rover" },
  { id: uuidv4(), make: "Jaguar" },
  { id: uuidv4(), make: "Infiniti" },
  { id: uuidv4(), make: "Acura" },
  { id: uuidv4(), make: "Mitsubishi" },
  { id: uuidv4(), make: "Buick" },
  { id: uuidv4(), make: "GMC" },
  { id: uuidv4(), make: "Cadillac" },
  { id: uuidv4(), make: "Chrysler" },
  { id: uuidv4(), make: "Fiat" },
  { id: uuidv4(), make: "Mini" },
  { id: uuidv4(), make: "Alfa Romeo" },
  { id: uuidv4(), make: "Maserati" },
  { id: uuidv4(), make: "Ferrari" },
  { id: uuidv4(), make: "Lamborghini" },
  { id: uuidv4(), make: "Bentley" },
  { id: uuidv4(), make: "Rolls-Royce" },
  { id: uuidv4(), make: "Aston Martin" },
  { id: uuidv4(), make: "McLaren" },
  { id: uuidv4(), make: "Pagani" },
  { id: uuidv4(), make: "Bugatti" },
  { id: uuidv4(), make: "Peugeot" },
  { id: uuidv4(), make: "Renault" },
  { id: uuidv4(), make: "Citroen" },
  { id: uuidv4(), make: "Opel" },
  { id: uuidv4(), make: "Vauxhall" },
  { id: uuidv4(), make: "Skoda" },
  { id: uuidv4(), make: "Seat" },
  { id: uuidv4(), make: "Saab" },
  { id: uuidv4(), make: "Suzuki" },
  { id: uuidv4(), make: "Isuzu" },
  { id: uuidv4(), make: "Daihatsu" },
  { id: uuidv4(), make: "Holden" },
  { id: uuidv4(), make: "Genesis" },
  { id: uuidv4(), make: "Lincoln" },
  { id: uuidv4(), make: "Hummer" },
  { id: uuidv4(), make: "Saturn" },
  { id: uuidv4(), make: "Oldsmobile" },
  { id: uuidv4(), make: "Pontiac" },
  { id: uuidv4(), make: "Plymouth" },
  { id: uuidv4(), make: "Geo" },
  { id: uuidv4(), make: "Scion" },
  { id: uuidv4(), make: "Rivian" },
  { id: uuidv4(), make: "Lucid" },
  { id: uuidv4(), make: "Polestar" },
  { id: uuidv4(), make: "Fisker" },
  { id: uuidv4(), make: "Koenigsegg" },
  { id: uuidv4(), make: "Spyker" },
  { id: uuidv4(), make: "Lotus" },
  { id: uuidv4(), make: "MG" },
  { id: uuidv4(), make: "Rover" },
  { id: uuidv4(), make: "Tata" },
  { id: uuidv4(), make: "Mahindra" },
  { id: uuidv4(), make: "Great Wall" },
  { id: uuidv4(), make: "BYD" },
  { id: uuidv4(), make: "Chery" },
  { id: uuidv4(), make: "Geely" },
  { id: uuidv4(), make: "Baojun" },
  { id: uuidv4(), make: "Zotye" },
  { id: uuidv4(), make: "Dongfeng" },
  { id: uuidv4(), make: "FAW" },
  { id: uuidv4(), make: "Lifan" },
  { id: uuidv4(), make: "JAC" },
  { id: uuidv4(), make: "Changan" },
  { id: uuidv4(), make: "GAC" },
  { id: uuidv4(), make: "Haval" },
  { id: uuidv4(), make: "Wuling" },
  { id: uuidv4(), make: "Nio" },
  { id: uuidv4(), make: "XPeng" },
  { id: uuidv4(), make: "VinFast" },
  { id: uuidv4(), make: "Dacia" },
  { id: uuidv4(), make: "Lada" },
  { id: uuidv4(), make: "UAZ" },
  { id: uuidv4(), make: "GAZ" },
  { id: uuidv4(), make: "Moskvich" },
  { id: uuidv4(), make: "ZAZ" },
  { id: uuidv4(), make: "Tatra" },
  { id: uuidv4(), make: "Wartburg" }
];

export const carModels = [
  [{ id: uuidv4(), model: "Corolla" }, { id: uuidv4(), model: "Camry" }, { id: uuidv4(), model: "RAV4" }, { id: uuidv4(), model: "Highlander" }, { id: uuidv4(), model: "Tacoma" }],
  [{ id: uuidv4(), model: "Civic" }, { id: uuidv4(), model: "Accord" }, { id: uuidv4(), model: "CR-V" }, { id: uuidv4(), model: "Pilot" }, { id: uuidv4(), model: "Fit" }],
  [{ id: uuidv4(), model: "F-150" }, { id: uuidv4(), model: "Mustang" }, { id: uuidv4(), model: "Explorer" }, { id: uuidv4(), model: "Focus" }, { id: uuidv4(), model: "Fusion" }],
  [{ id: uuidv4(), model: "Silverado" }, { id: uuidv4(), model: "Malibu" }, { id: uuidv4(), model: "Equinox" }, { id: uuidv4(), model: "Tahoe" }, { id: uuidv4(), model: "Impala" }],
  [{ id: uuidv4(), model: "Altima" }, { id: uuidv4(), model: "Sentra" }, { id: uuidv4(), model: "Rogue" }, { id: uuidv4(), model: "Pathfinder" }, { id: uuidv4(), model: "Versa" }],
  [{ id: uuidv4(), model: "3 Series" }, { id: uuidv4(), model: "5 Series" }, { id: uuidv4(), model: "X5" }, { id: uuidv4(), model: "X3" }, { id: uuidv4(), model: "7 Series" }],
  [{ id: uuidv4(), model: "C-Class" }, { id: uuidv4(), model: "E-Class" }, { id: uuidv4(), model: "GLC" }, { id: uuidv4(), model: "GLE" }, { id: uuidv4(), model: "S-Class" }],
  [{ id: uuidv4(), model: "Golf" }, { id: uuidv4(), model: "Passat" }, { id: uuidv4(), model: "Tiguan" }, { id: uuidv4(), model: "Polo" }, { id: uuidv4(), model: "Jetta" }],
  [{ id: uuidv4(), model: "A4" }, { id: uuidv4(), model: "A6" }, { id: uuidv4(), model: "Q5" }, { id: uuidv4(), model: "Q7" }, { id: uuidv4(), model: "A3" }],
  [{ id: uuidv4(), model: "Elantra" }, { id: uuidv4(), model: "Sonata" }, { id: uuidv4(), model: "Tucson" }, { id: uuidv4(), model: "Santa Fe" }, { id: uuidv4(), model: "Accent" }],
  [{ id: uuidv4(), model: "Soul" }, { id: uuidv4(), model: "Sportage" }, { id: uuidv4(), model: "Sorento" }, { id: uuidv4(), model: "Optima" }, { id: uuidv4(), model: "Stinger" }],
  [{ id: uuidv4(), model: "Mazda3" }, { id: uuidv4(), model: "Mazda6" }, { id: uuidv4(), model: "CX-5" }, { id: uuidv4(), model: "CX-9" }, { id: uuidv4(), model: "MX-5" }],
  [{ id: uuidv4(), model: "Outback" }, { id: uuidv4(), model: "Forester" }, { id: uuidv4(), model: "Impreza" }, { id: uuidv4(), model: "Legacy" }, { id: uuidv4(), model: "Ascent" }],
  [{ id: uuidv4(), model: "RX" }, { id: uuidv4(), model: "ES" }, { id: uuidv4(), model: "NX" }, { id: uuidv4(), model: "GX" }, { id: uuidv4(), model: "LS" }],
  [{ id: uuidv4(), model: "Wrangler" }, { id: uuidv4(), model: "Grand Cherokee" }, { id: uuidv4(), model: "Cherokee" }, { id: uuidv4(), model: "Compass" }, { id: uuidv4(), model: "Renegade" }],
  [{ id: uuidv4(), model: "Charger" }, { id: uuidv4(), model: "Challenger" }, { id: uuidv4(), model: "Durango" }, { id: uuidv4(), model: "Journey" }, { id: uuidv4(), model: "Viper" }],
  [{ id: uuidv4(), model: "1500" }, { id: uuidv4(), model: "2500" }, { id: uuidv4(), model: "3500" }, { id: uuidv4(), model: "ProMaster" }, { id: uuidv4(), model: "Dakota" }],
  [{ id: uuidv4(), model: "Model S" }, { id: uuidv4(), model: "Model 3" }, { id: uuidv4(), model: "Model X" }, { id: uuidv4(), model: "Model Y" }, { id: uuidv4(), model: "Roadster" }],
  [{ id: uuidv4(), model: "XC90" }, { id: uuidv4(), model: "XC60" }, { id: uuidv4(), model: "S60" }, { id: uuidv4(), model: "V60" }, { id: uuidv4(), model: "XC40" }],
  [{ id: uuidv4(), model: "911" }, { id: uuidv4(), model: "Cayenne" }, { id: uuidv4(), model: "Macan" }, { id: uuidv4(), model: "Panamera" }, { id: uuidv4(), model: "Taycan" }],
  [{ id: uuidv4(), model: "Range Rover" }, { id: uuidv4(), model: "Discovery" }, { id: uuidv4(), model: "Defender" }, { id: uuidv4(), model: "Evoque" }, { id: uuidv4(), model: "Velar" }],
  [{ id: uuidv4(), model: "XF" }, { id: uuidv4(), model: "XE" }, { id: uuidv4(), model: "F-Pace" }, { id: uuidv4(), model: "E-Pace" }, { id: uuidv4(), model: "F-Type" }],
  [{ id: uuidv4(), model: "Q50" }, { id: uuidv4(), model: "Q60" }, { id: uuidv4(), model: "QX60" }, { id: uuidv4(), model: "QX80" }, { id: uuidv4(), model: "QX50" }],
  [{ id: uuidv4(), model: "MDX" }, { id: uuidv4(), model: "RDX" }, { id: uuidv4(), model: "TLX" }, { id: uuidv4(), model: "ILX" }, { id: uuidv4(), model: "NSX" }],
  [{ id: uuidv4(), model: "Outlander" }, { id: uuidv4(), model: "Eclipse Cross" }, { id: uuidv4(), model: "Lancer" }, { id: uuidv4(), model: "Mirage" }, { id: uuidv4(), model: "Pajero" }],
  [{ id: uuidv4(), model: "Enclave" }, { id: uuidv4(), model: "Encore" }, { id: uuidv4(), model: "Regal" }, { id: uuidv4(), model: "LaCrosse" }, { id: uuidv4(), model: "Verano" }],
  [{ id: uuidv4(), model: "Sierra" }, { id: uuidv4(), model: "Yukon" }, { id: uuidv4(), model: "Acadia" }, { id: uuidv4(), model: "Canyon" }, { id: uuidv4(), model: "Terrain" }],
  [{ id: uuidv4(), model: "Escalade" }, { id: uuidv4(), model: "CTS" }, { id: uuidv4(), model: "XT5" }, { id: uuidv4(), model: "XT6" }, { id: uuidv4(), model: "ATS" }],
  [{ id: uuidv4(), model: "Pacifica" }, { id: uuidv4(), model: "300" }, { id: uuidv4(), model: "Voyager" }, { id: uuidv4(), model: "Aspen" }, { id: uuidv4(), model: "Crossfire" }],
  [{ id: uuidv4(), model: "500" }, { id: uuidv4(), model: "Panda" }, { id: uuidv4(), model: "Tipo" }, { id: uuidv4(), model: "Punto" }, { id: uuidv4(), model: "Ducato" }],
  [{ id: uuidv4(), model: "Cooper" }, { id: uuidv4(), model: "Countryman" }, { id: uuidv4(), model: "Clubman" }, { id: uuidv4(), model: "Paceman" }, { id: uuidv4(), model: "Roadster" }],
  [{ id: uuidv4(), model: "Giulia" }, { id: uuidv4(), model: "Stelvio" }, { id: uuidv4(), model: "4C" }, { id: uuidv4(), model: "MiTo" }, { id: uuidv4(), model: "GTV" }],
  [{ id: uuidv4(), model: "Ghibli" }, { id: uuidv4(), model: "Levante" }, { id: uuidv4(), model: "Quattroporte" }, { id: uuidv4(), model: "GranTurismo" }, { id: uuidv4(), model: "MC20" }],
  [{ id: uuidv4(), model: "488" }, { id: uuidv4(), model: "Portofino" }, { id: uuidv4(), model: "812" }, { id: uuidv4(), model: "Roma" }, { id: uuidv4(), model: "LaFerrari" }],
  [{ id: uuidv4(), model: "Huracan" }, { id: uuidv4(), model: "Aventador" }, { id: uuidv4(), model: "Urus" }, { id: uuidv4(), model: "Gallardo" }, { id: uuidv4(), model: "Murcielago" }],
  [{ id: uuidv4(), model: "Bentayga" }, { id: uuidv4(), model: "Continental GT" }, { id: uuidv4(), model: "Flying Spur" }, { id: uuidv4(), model: "Mulsanne" }, { id: uuidv4(), model: "Azure" }],
  [{ id: uuidv4(), model: "Phantom" }, { id: uuidv4(), model: "Ghost" }, { id: uuidv4(), model: "Wraith" }, { id: uuidv4(), model: "Dawn" }, { id: uuidv4(), model: "Cullinan" }],
  [{ id: uuidv4(), model: "DB11" }, { id: uuidv4(), model: "Vantage" }, { id: uuidv4(), model: "DBX" }, { id: uuidv4(), model: "Rapide" }, { id: uuidv4(), model: "Vanquish" }],
  [{ id: uuidv4(), model: "720S" }, { id: uuidv4(), model: "570S" }, { id: uuidv4(), model: "600LT" }, { id: uuidv4(), model: "P1" }, { id: uuidv4(), model: "GT" }],
  [{ id: uuidv4(), model: "Huayra" }, { id: uuidv4(), model: "Zonda" }, { id: uuidv4(), model: "Imola" }, { id: uuidv4(), model: "R" }, { id: uuidv4(), model: "C12" }],
  [{ id: uuidv4(), model: "Chiron" }, { id: uuidv4(), model: "Veyron" }, { id: uuidv4(), model: "Divo" }, { id: uuidv4(), model: "Centodieci" }, { id: uuidv4(), model: "Bolide" }],
  [{ id: uuidv4(), model: "208" }, { id: uuidv4(), model: "308" }, { id: uuidv4(), model: "508" }, { id: uuidv4(), model: "2008" }, { id: uuidv4(), model: "3008" }],
  [{ id: uuidv4(), model: "Clio" }, { id: uuidv4(), model: "Megane" }, { id: uuidv4(), model: "Kadjar" }, { id: uuidv4(), model: "Captur" }, { id: uuidv4(), model: "Zoe" }],
  [{ id: uuidv4(), model: "C3" }, { id: uuidv4(), model: "C4" }, { id: uuidv4(), model: "C5" }, { id: uuidv4(), model: "Berlingo" }, { id: uuidv4(), model: "Aircross" }],
  [{ id: uuidv4(), model: "Corsa" }, { id: uuidv4(), model: "Astra" }, { id: uuidv4(), model: "Insignia" }, { id: uuidv4(), model: "Mokka" }, { id: uuidv4(), model: "Crossland" }],
  [{ id: uuidv4(), model: "Astra" }, { id: uuidv4(), model: "Corsa" }, { id: uuidv4(), model: "Insignia" }, { id: uuidv4(), model: "Crossland" }, { id: uuidv4(), model: "Grandland" }],
  [{ id: uuidv4(), model: "Fabia" }, { id: uuidv4(), model: "Octavia" }, { id: uuidv4(), model: "Superb" }, { id: uuidv4(), model: "Kodiaq" }, { id: uuidv4(), model: "Karoq" }],
  [{ id: uuidv4(), model: "Ibiza" }, { id: uuidv4(), model: "Leon" }, { id: uuidv4(), model: "Ateca" }, { id: uuidv4(), model: "Arona" }, { id: uuidv4(), model: "Tarraco" }],
  [{ id: uuidv4(), model: "900" }, { id: uuidv4(), model: "9-3" }, { id: uuidv4(), model: "9-5" }, { id: uuidv4(), model: "9000" }, { id: uuidv4(), model: "92" }],
  [{ id: uuidv4(), model: "Swift" }, { id: uuidv4(), model: "Vitara" }, { id: uuidv4(), model: "Jimny" }, { id: uuidv4(), model: "Baleno" }, { id: uuidv4(), model: "Ignis" }],
  [{ id: uuidv4(), model: "D-Max" }, { id: uuidv4(), model: "MU-X" }, { id: uuidv4(), model: "Trooper" }, { id: uuidv4(), model: "Rodeo" }, { id: uuidv4(), model: "Vehicross" }],
  [{ id: uuidv4(), model: "Charade" }, { id: uuidv4(), model: "Terios" }, { id: uuidv4(), model: "Sirion" }, { id: uuidv4(), model: "Copen" }, { id: uuidv4(), model: "Mira" }],
  [{ id: uuidv4(), model: "Commodore" }, { id: uuidv4(), model: "Monaro" }, { id: uuidv4(), model: "Ute" }, { id: uuidv4(), model: "Caprice" }, { id: uuidv4(), model: "Calais" }],
  [{ id: uuidv4(), model: "G80" }, { id: uuidv4(), model: "G90" }, { id: uuidv4(), model: "GV70" }, { id: uuidv4(), model: "GV80" }, { id: uuidv4(), model: "G70" }],
  [{ id: uuidv4(), model: "Navigator" }, { id: uuidv4(), model: "Aviator" }, { id: uuidv4(), model: "Corsair" }, { id: uuidv4(), model: "MKX" }, { id: uuidv4(), model: "MKT" }],
  [{ id: uuidv4(), model: "H1" }, { id: uuidv4(), model: "H2" }, { id: uuidv4(), model: "H3" }, { id: uuidv4(), model: "H2 SUT" }, { id: uuidv4(), model: "H3T" }],
  [{ id: uuidv4(), model: "Vue" }, { id: uuidv4(), model: "Ion" }, { id: uuidv4(), model: "Sky" }, { id: uuidv4(), model: "Outlook" }, { id: uuidv4(), model: "Aura" }],
  [{ id: uuidv4(), model: "Alero" }, { id: uuidv4(), model: "Silhouette" }, { id: uuidv4(), model: "Aurora" }, { id: uuidv4(), model: "Bravada" }, { id: uuidv4(), model: "Cutlass" }],
  [{ id: uuidv4(), model: "GTO" }, { id: uuidv4(), model: "Firebird" }, { id: uuidv4(), model: "Grand Prix" }, { id: uuidv4(), model: "Bonneville" }, { id: uuidv4(), model: "Solstice" }],
  [{ id: uuidv4(), model: "Voyager" }, { id: uuidv4(), model: "Neon" }, { id: uuidv4(), model: "Breeze" }, { id: uuidv4(), model: "Prowler" }, { id: uuidv4(), model: "Horizon" }],
  [{ id: uuidv4(), model: "Metro" }, { id: uuidv4(), model: "Tracker" }, { id: uuidv4(), model: "Prizm" }, { id: uuidv4(), model: "Storm" }, { id: uuidv4(), model: "Spectrum" }],
  [{ id: uuidv4(), model: "xB" }, { id: uuidv4(), model: "tC" }, { id: uuidv4(), model: "xD" }, { id: uuidv4(), model: "FR-S" }, { id: uuidv4(), model: "iQ" }],
  [{ id: uuidv4(), model: "R1T" }, { id: uuidv4(), model: "R1S" }],
  [{ id: uuidv4(), model: "Air" }, { id: uuidv4(), model: "Gravity" }],
  [{ id: uuidv4(), model: "2" }, { id: uuidv4(), model: "3" }, { id: uuidv4(), model: "Precept" }],
  [{ id: uuidv4(), model: "Ocean" }],
  [{ id: uuidv4(), model: "Agera" }, { id: uuidv4(), model: "Regera" }, { id: uuidv4(), model: "Jesko" }],
  [{ id: uuidv4(), model: "C8" }, { id: uuidv4(), model: "C12" }, { id: uuidv4(), model: "C8 Spyder" }],
  [{ id: uuidv4(), model: "Elise" }, { id: uuidv4(), model: "Evora" }, { id: uuidv4(), model: "Exige" }, { id: uuidv4(), model: "Emira" }, { id: uuidv4(), model: "Eletre" }],
  [{ id: uuidv4(), model: "MG3" }, { id: uuidv4(), model: "ZS" }, { id: uuidv4(), model: "HS" }, { id: uuidv4(), model: "MG6" }, { id: uuidv4(), model: "MG5" }],
  [{ id: uuidv4(), model: "400" }, { id: uuidv4(), model: "600" }, { id: uuidv4(), model: "75" }, { id: uuidv4(), model: "Metro" }, { id: uuidv4(), model: "200" }],
  [{ id: uuidv4(), model: "Nano" }, { id: uuidv4(), model: "Safari" }, { id: uuidv4(), model: "Harrier" }, { id: uuidv4(), model: "Tiago" }, { id: uuidv4(), model: "Nexon" }],
  [{ id: uuidv4(), model: "Scorpio" }, { id: uuidv4(), model: "Bolero" }, { id: uuidv4(), model: "XUV500" }, { id: uuidv4(), model: "Thar" }, { id: uuidv4(), model: "TUV300" }],
  [{ id: uuidv4(), model: "Steed" }, { id: uuidv4(), model: "Haval H6" }, { id: uuidv4(), model: "Haval H9" }, { id: uuidv4(), model: "C30" }, { id: uuidv4(), model: "C50" }],
  [{ id: uuidv4(), model: "Han" }, { id: uuidv4(), model: "Tang" }, { id: uuidv4(), model: "Qin" }, { id: uuidv4(), model: "Song" }, { id: uuidv4(), model: "Yuan" }],
  [{ id: uuidv4(), model: "Tiggo" }, { id: uuidv4(), model: "Arrizo" }, { id: uuidv4(), model: "QQ" }, { id: uuidv4(), model: "Jetour" }, { id: uuidv4(), model: "Tiggo 8" }],
  [{ id: uuidv4(), model: "Emgrand" }, { id: uuidv4(), model: "Atlas" }, { id: uuidv4(), model: "Panda" }, { id: uuidv4(), model: "Boyue" }, { id: uuidv4(), model: "GC9" }],
  [{ id: uuidv4(), model: "510" }, { id: uuidv4(), model: "530" }, { id: uuidv4(), model: "560" }, { id: uuidv4(), model: "RS-5" }, { id: uuidv4(), model: "630" }],
  [{ id: uuidv4(), model: "T600" }, { id: uuidv4(), model: "SR9" }, { id: uuidv4(), model: "T300" }, { id: uuidv4(), model: "Z300" }, { id: uuidv4(), model: "Z500" }],
  [{ id: uuidv4(), model: "AX7" }, { id: uuidv4(), model: "AX5" }, { id: uuidv4(), model: "A9" }, { id: uuidv4(), model: "Joyear" }, { id: uuidv4(), model: "Rich" }],
  [{ id: uuidv4(), model: "Besturn B30" }, { id: uuidv4(), model: "Besturn X40" }, { id: uuidv4(), model: "Hongqi H5" }, { id: uuidv4(), model: "Hongqi H7" }, { id: uuidv4(), model: "Xenia R7" }],
  [{ id: uuidv4(), model: "Breez" }, { id: uuidv4(), model: "Solano" }, { id: uuidv4(), model: "Myway" }, { id: uuidv4(), model: "X60" }, { id: uuidv4(), model: "X70" }],
  [{ id: uuidv4(), model: "S2" }, { id: uuidv4(), model: "S3" }, { id: uuidv4(), model: "S5" }, { id: uuidv4(), model: "T40" }, { id: uuidv4(), model: "T50" }],
  [{ id: uuidv4(), model: "CS75" }, { id: uuidv4(), model: "CS35" }, { id: uuidv4(), model: "Eado" }, { id: uuidv4(), model: "Raeton" }, { id: uuidv4(), model: "BenBen" }],
  [{ id: uuidv4(), model: "GS4" }, { id: uuidv4(), model: "GS8" }, { id: uuidv4(), model: "GA8" }, { id: uuidv4(), model: "GA6" }, { id: uuidv4(), model: "GE3" }],
  [{ id: uuidv4(), model: "H2" }, { id: uuidv4(), model: "H6" }, { id: uuidv4(), model: "H9" }, { id: uuidv4(), model: "F7" }, { id: uuidv4(), model: "M6" }],
  [{ id: uuidv4(), model: "Mini EV" }, { id: uuidv4(), model: "Cortez" }, { id: uuidv4(), model: "Confero" }, { id: uuidv4(), model: "Formo" }, { id: uuidv4(), model: "Almaz" }],
  [{ id: uuidv4(), model: "ES8" }, { id: uuidv4(), model: "ES6" }, { id: uuidv4(), model: "EC6" }, { id: uuidv4(), model: "ET7" }, { id: uuidv4(), model: "ET5" }],
  [{ id: uuidv4(), model: "G3" }, { id: uuidv4(), model: "P7" }, { id: uuidv4(), model: "G6" }, { id: uuidv4(), model: "P5" }, { id: uuidv4(), model: "G9" }],
  [{ id: uuidv4(), model: "Lux A2.0" }, { id: uuidv4(), model: "Lux SA2.0" }, { id: uuidv4(), model: "President" }, { id: uuidv4(), model: "Fadil" }, { id: uuidv4(), model: "VF e34" }],
  [{ id: uuidv4(), model: "Sandero" }, { id: uuidv4(), model: "Duster" }, { id: uuidv4(), model: "Logan" }, { id: uuidv4(), model: "Lodgy" }, { id: uuidv4(), model: "Dokker" }],
  [{ id: uuidv4(), model: "Vesta" }, { id: uuidv4(), model: "Granta" }, { id: uuidv4(), model: "XRAY" }, { id: uuidv4(), model: "Largus" }, { id: uuidv4(), model: "Kalina" }],
  [{ id: uuidv4(), model: "Patriot" }, { id: uuidv4(), model: "Hunter" }, { id: uuidv4(), model: "Pickup" }, { id: uuidv4(), model: "Cargo" }, { id: uuidv4(), model: "Simbir" }],
  [{ id: uuidv4(), model: "Volga" }, { id: uuidv4(), model: "Sobol" }, { id: uuidv4(), model: "GAZelle" }, { id: uuidv4(), model: "Sadko" }, { id: uuidv4(), model: "Valdai" }],
  [{ id: uuidv4(), model: "2141" }, { id: uuidv4(), model: "Moskvich 3" }, { id: uuidv4(), model: "Moskvich 408" }, { id: uuidv4(), model: "Moskvich 412" }, { id: uuidv4(), model: "Moskvich 2140" }],
  [{ id: uuidv4(), model: "Tavria" }, { id: uuidv4(), model: "Slavuta" }, { id: uuidv4(), model: "Forza" }, { id: uuidv4(), model: "Sens" }, { id: uuidv4(), model: "Chance" }],
  [{ id: uuidv4(), model: "T600" }, { id: uuidv4(), model: "T700" }, { id: uuidv4(), model: "T815" }, { id: uuidv4(), model: "T161" }, { id: uuidv4(), model: "T138" }],
  [{ id: uuidv4(), model: "353" }, { id: uuidv4(), model: "311" }, { id: uuidv4(), model: "1.3" }, { id: uuidv4(), model: "1.1" }, { id: uuidv4(), model: "1.0" }]
];
